// Generated by Wrangler on Thu Oct 10 2024 01:09:41 GMT+0900 (日本標準時)
// by running `wrangler types`

interface Env {
	SUPABASE_URL: "https://lyfolpqxqktrbmnuhghc.supabase.co";
	SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5Zm9scHF4cWt0cmJtbnVoZ2hjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjgzODczODUsImV4cCI6MjA0Mzk2MzM4NX0.T7-Y6q3tBmfDWDq5scg1bMK7HA5j49tHxrPywr6YzrI";
}
