// Generated by Wrangler on Sun Nov 24 2024 16:20:02 GMT+0900 (日本標準時)
// by running `wrangler types`

interface Env {
	SUPABASE_URL: "https://bppgbaxsswwmvfxabgmk.supabase.co";
	SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwcGdiYXhzc3d3bXZmeGFiZ21rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI0MjU4NTAsImV4cCI6MjA0ODAwMTg1MH0.FpMNmi6WIcFmvDzp0AkPam2Vxe7D7wurKNfe2V07A_c";
	LAST_FM_API_KEY: string;
}
